# Generated by Django 2.2.5 on 2019-09-08 15:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='subdomain',
        ),
        migrations.RemoveField(
            model_name='team',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('happiness', models.IntegerField(blank=True, null=True,
                                                  validators=[
                                                      django.core.validators.MinValueValidator(
                                                          1),
                                                      django.core.validators.MaxValueValidator(
                                                          5)])),
                ('team', models.ForeignKey(blank=True, null=True,
                                           on_delete=django.db.models.deletion.CASCADE,
                                           to='teams.Team')),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberHappiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='teams.TeamMember')),
            ],
        ),
    ]
