# Generated by Django 2.2.5 on 2019-09-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_auto_20190909_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberhappiness',
            name='happiness',
            field=models.IntegerField(
                choices=[(1, 'Unhappy'), (3, 'Neutral'), (5, 'Very Happy')]),
        ),
    ]
